### ISSUE TITLE
I'm blocked for no resoan

### ISSUE THREAD

**Issue by MarufKhan8307** [mrepol742/project-orion#99]
______________________________
Bro please unblock me from the prj orion server of yours . I added a instance earlier. and also make a video on how to actually host the bot bcoz it ain't working. There's lots of errors

Bot name : Sora chan
Owner : Tera byte

**Comment by mrepol742** [comment]
Hello, please reply your uid, and I'll unblock it once im able to resolve the root permission in my server.

And make sure your forked is always up to date from this repository.


Preferably u need to have  VPS.

Run npm i then npm run start to initiate the project.
if u want to add the instance manually u need to hit 'control + c' to stop the server and add the instance in '/data/cookies/' forder name 'new.bin' and run the bot again

else

you will paste the instance in the console.


![received_2509944599214112.jpeg](https://github.com/mrepol742/project-orion/assets/62317165/1f1b0ea6-6cdb-4564-a309-5baa9f80af6f)

**Comment by MarufKhan8307** [comment]
Bro can you make a tutorial how to fork your project orion bot and run it
smoothly ? render says no account found, and I have no idea how to add an
account. Please make a tutoria[image: image.png][image: image.png]
.
